### PR TITLE
Renovate/restdocs api spec

### PR DESCRIPTION
**Pull request by ioanngolovko**
Hey there!

I finished the bot job.
I have some notions here.

1. restdocs-api-spec v0.17.1 requires java 17 as minimal so I upgraded it.
2. I had problems with guice injection of collection into SpecificationGeneratorFactory with java 17. So this is the only solution that works. 
3. To build it local you should have JAVA_HOME that refers to java 17 due to maven-invoker-plugin (integration tests).

Our team likes this tool, but it's the last point of our migration to java 17 and spring boot 3. So we can't wait of new updates from sisu and guice.  This my version is stable one. 

I suggest to tag next version as 1.0 due to breaking changes.

### CODE REVIEW

**Review by bomzheg — APPROVED** [review]

**Comment by comrada** [comment]
Any progress mates?

**Comment by ioanngolovko** [comment]
> Any progress mates?

Workflow not approved yet. We can't go on like this.

**Comment by norbertoritzmann** [comment]
The PR looks good and very awaited.

**Comment by ioanngolovko** [comment]
The only thing missing is additional processing of `formParameters`  . I hope we can add it with another enhancement.  This will allow the teams to update their stack.

**Comment by erlandamansaku** [comment]
> > Any progress mates?
> 
> Workflow not approved yet. We can't go on like this.

Who is responsible for the approval? Maybe we should contact him?

**Comment by ioanngolovko** [comment]
> > > Any progress mates?
> > 
> > 
> > Workflow not approved yet. We can't go on like this.
> 
> Who is responsible for the approval? Maybe we should contact him?

Found one on linkedin. Hope it works.

**Comment by klieber** [comment]
Hey all!  Sorry, I don't really use this anymore so it doesn't get much attention from me.  I'll try to take a look and help you get this merged.

**Comment by klieber** [comment]
For some reason this isn't building even after I approved the workflow.  I don't seem to have any buttons to force it to build either.  Not sure if this is just because it's a branch in your fork so maybe you have to kick it off?  Another option would be to try adding another commit to see if that triggers it.

**Comment by ioanngolovko** [comment]
I created another pull request into the feature branch.
I hope if we merge it then working one starts.

My new one.
https://github.com/BerkleyTechnologyServices/restdocs-spec/pull/236

PR from the bot
https://github.com/BerkleyTechnologyServices/restdocs-spec/pull/214

**Pull request closed without merging**
