### PR TITLE
Add support for generating more hosts to OpenAPI 3.0 specification. 

### PR DESCRIPTION
**Pull request by DavidBulawa98**
Maintains backward compatibility.

### CODE REVIEW

**Comment by ohjongsung** [comment]
Please merge this feature.

**Comment by woo-yu** [comment]
@klieber Hello. I'm sorry to mention, but I really need this feature. Could you review it?

**Comment by klieber** [comment]
I manually merged this: https://github.com/BerkleyTechnologyServices/restdocs-spec/commit/8c8802d57cd0d082a8090d37654fab332d164feb

**Comment by woo-yu** [comment]
@klieber I appreciate your kindness. then... Could you please make a suggestion?
I use Java 8, so I want backport for version 0.21.
Thank you for your consideration. 🙇‍♀️

**Comment by klieber** [comment]
Sorry, Java 8 is over 9 years old and most main stream libraries haven't supported it for a long time now. Also, I'm just one person and don't even use this project anymore so I definitely don't have time to support old versions of Java. You should really consider upgrading.

**Pull request closed without merging**
